In [1]:
import pandas as pd


users = pd.DataFrame([
    [1, 'Alice', 'female', '23', 'China ', '2023-01-15'],
    [2, 'Bob', 'male', '31', 'USA', '2023-03-20'],
    [3, 'Cathy', 'female', None, 'china', '2023-02-11'],
    [4, 'David', 'male', '27', 'UK', '2023-05-09'],
    [5, 'Eva', 'female', '35', 'USA ', '2023-04-01'],
    [6, 'Frank', 'male', '19', None, '2023-06-18'],
], columns=['user_id', 'name', 'gender', 'age', 'country', 'signup_date'])


products = pd.DataFrame([
    [101, 'Keyboard', 'Electronics', '199'],
    [102, 'Mouse', 'Electronics', '99'],
    [103, 'Monitor', 'Electronics', '1299'],
    [104, 'Desk', 'Furniture', '899'],
    [105, 'Chair', 'Furniture', '499'],
    [106, 'Notebook', 'Stationery', '15'],
], columns=['product_id', 'product_name', 'category', 'price'])


orders = pd.DataFrame([
    [1001, 1, 101, '2', '2024-01-03 10:15', 'paid', '0'],
    [1002, 2, 103, '1', '2024-01-05 14:20', 'paid', '100'],
    [1003, 1, 106, '5', '2024-01-08 09:00', 'paid', None],
    [1004, 3, 102, '3', '2024-01-08 21:10', 'cancelled', '0'],
    [1005, 4, 104, '1', '2024-02-01 11:30', 'paid', '50'],
    [1006, 5, 105, '2', '2024-02-03 16:45', 'paid', '0'],
    [1007, 2, 101, '1', '2024-02-10 08:00', 'refunded', '0'],
    [1008, 6, 106, '10', '2024-02-12 19:20', 'paid', '5'],
    [1009, 1, 103, '1', '2024-02-15 13:00', 'paid', '200'],
    [1010, 3, 105, '1', '2024-03-01 10:10', 'paid', None],
    [1011, 5, 101, '2', '2024-03-03 12:00', 'paid', '20'],
    [1012, 2, 104, '1', '2024-03-05 18:30', 'paid', '0'],
    [1013, 2, 104, '1', '2024-03-05 18:30', 'paid', '0'],   # 故意重复
], columns=['order_id', 'user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'])

In [2]:
users.head(3)

   user_id   name  gender  age country signup_date
0        1  Alice  female   23  China   2023-01-15
1        2    Bob    male   31     USA  2023-03-20
2        3  Cathy  female  NaN   china  2023-02-11

In [3]:
users.shape

(6, 6)

In [4]:
users.dtypes

user_id        int64
name             str
gender           str
age              str
country          str
signup_date      str
dtype: object

In [5]:
users.isna().sum().sum()

np.int64(2)

In [6]:
filt = users['country'].notna() & (users['country'] != users['country'].str.strip().str.title())
users[filt]

   user_id   name  gender  age country signup_date
0        1  Alice  female   23  China   2023-01-15
1        2    Bob    male   31     USA  2023-03-20
2        3  Cathy  female  NaN   china  2023-02-11
3        4  David    male   27      UK  2023-05-09
4        5    Eva  female   35    USA   2023-04-01

In [7]:
filt = users['age'].str.isdigit().fillna(False)
users[~filt]

   user_id   name  gender  age country signup_date
2        3  Cathy  female  NaN   china  2023-02-11

In [8]:
filt = (orders['quantity'].str.isdigit().fillna(False)) & (orders['discount'].str.isdigit().fillna(False))
orders[~filt]

   order_id  user_id  product_id quantity        order_time status discount
2      1003        1         106        5  2024-01-08 09:00   paid      NaN
9      1010        3         105        1  2024-03-01 10:10   paid      NaN

In [9]:
filt = orders.duplicated(
    subset = ['user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'],
    keep = False
)
orders[filt]

    order_id  user_id  product_id quantity        order_time status discount
11      1012        2         104        1  2024-03-05 18:30   paid        0
12      1013        2         104        1  2024-03-05 18:30   paid        0

In [10]:
users['country'] = users['country'].str.strip().str.title()
users

   user_id   name  gender  age country signup_date
0        1  Alice  female   23   China  2023-01-15
1        2    Bob    male   31     Usa  2023-03-20
2        3  Cathy  female  NaN   China  2023-02-11
3        4  David    male   27      Uk  2023-05-09
4        5    Eva  female   35     Usa  2023-04-01
5        6  Frank    male   19     NaN  2023-06-18

In [11]:
users['age'] = users['age'].astype(float)
users

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
1        2    Bob    male  31.0     Usa  2023-03-20
2        3  Cathy  female   NaN   China  2023-02-11
3        4  David    male  27.0      Uk  2023-05-09
4        5    Eva  female  35.0     Usa  2023-04-01
5        6  Frank    male  19.0     NaN  2023-06-18

In [12]:
users['signup_date'] = pd.to_datetime(users['signup_date'])
users

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
1        2    Bob    male  31.0     Usa  2023-03-20
2        3  Cathy  female   NaN   China  2023-02-11
3        4  David    male  27.0      Uk  2023-05-09
4        5    Eva  female  35.0     Usa  2023-04-01
5        6  Frank    male  19.0     NaN  2023-06-18

In [13]:
orders['quantity'] = orders['quantity'].astype(float)
orders['discount'] = orders['discount'].astype(float)

In [14]:
orders['order_time'] = pd.to_datetime(orders['order_time'])
orders

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,NaN
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,NaN
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0
12,1013,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [15]:
orders = orders.drop_duplicates(
    subset = ['user_id', 'product_id', 'quantity', 'order_time', 'status', 'discount'],
    keep = 'first'    
)

In [16]:
orders['discount'] = orders['discount'].fillna(0)
orders

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [17]:
filt = users['country'] == 'China'
users[filt]

   user_id   name  gender   age country signup_date
0        1  Alice  female  23.0   China  2023-01-15
2        3  Cathy  female   NaN   China  2023-02-11

In [18]:
filt = (users['age'] > 25) & (users['gender'] == 'female')
users[filt]

   user_id name  gender   age country signup_date
4        5  Eva  female  35.0     Usa  2023-04-01

In [19]:
filt = (orders['status'] == 'paid')
orders[filt]

,order_id,user_id,product_id,quantity,order_time,status,discount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0

In [20]:
# filt = orders['order_time'].dt.month == 2
# orders[filt]
filt = (orders['order_time'] >= '2024-02-01') & (orders['order_time'] < '2024-03-01')
orders[filt]

,order_id,user_id,product_id,quantity,order_time,status,discount
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0

In [21]:
orders['month'] = orders['order_time'].dt.strftime('%Y') + '-' + orders['order_time'].dt.strftime('%m')
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03

In [22]:
orders['hour'] = orders['order_time'].dt.strftime('%H')
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18

In [23]:
orders['is_weekend'] = orders['order_time'].dt.dayofweek > 5
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13,False
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False

In [24]:
orders['final_amount'] = products.set_index('product_id').loc[orders['product_id'], 'price'].reset_index(drop=True).astype(float) * orders['quantity'] - orders['discount']
orders

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend,final_amount
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False,398.0
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False,1199.0
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False,75.0
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False,297.0
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False,849.0
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False,998.0
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False,199.0
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False,145.0
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13,False,1099.0
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False,499.0
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True,378.0
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False,899.0

In [25]:
df_all = orders
df_all['user_name'] = df_all['user_id'].map(users.set_index('user_id')['name'])
df_all['user_country'] = df_all['user_name'].map(users.set_index('name')['country'])
df_all['product_name'] = df_all['product_id'].map(products.set_index('product_id')['product_name'])
df_all['product_category'] = df_all['product_name'].map(products.set_index('product_name')['category'])
df_all['product_price'] = df_all['product_name'].map(products.set_index('product_name')['price'])
df_all['final_amount'] = df_all['quantity'].astype(float) * df_all['product_price'].astype(float)
df_all

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend,final_amount,user_name,user_country,product_name,product_category,product_price
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False,398.0,Alice,China,Keyboard,Electronics,199
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False,1299.0,Bob,Usa,Monitor,Electronics,1299
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False,75.0,Alice,China,Notebook,Stationery,15
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False,297.0,Cathy,China,Mouse,Electronics,99
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False,899.0,David,Uk,Desk,Furniture,899
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False,998.0,Eva,Usa,Chair,Furniture,499
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False,199.0,Bob,Usa,Keyboard,Electronics,199
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False,150.0,Frank,NaN,Notebook,Stationery,15
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13,False,1299.0,Alice,China,Monitor,Electronics,1299
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False,499.0,Cathy,China,Chair,Furniture,499
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True,398.0,Eva,Usa,Keyboard,Electronics,199
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False,899.0,Bob,Usa,Desk,Furniture,899

In [26]:
df_all = orders.merge(
    users[['user_id', 'name', 'country']],
    on='user_id',
    how='left'
).merge(
    products[['product_id', 'product_name', 'category', 'price']],
    on='product_id',
    how='left'
)
df_all['discount'] = df_all['discount'].fillna(0)
df_all = df_all.rename(columns={
    'name': 'user_name',
    'country': 'user_country',
    'category': 'product_category',
    'price': 'product_price'
})

df_all['final_amount'] = df_all['quantity'].astype(float) * df_all['product_price'].astype(float) - df_all['discount'].astype(float)

df_all

ValueError: cannot reindex on an axis with duplicate labels

In [ ]:
group_country = df_all.groupby('user_country')
group_country['order_id'].count()

In [ ]:
group_country['final_amount'].sum()

In [ ]:
average = group_country['final_amount'].sum() / group_country['order_id'].count()
average

In [ ]:
group_country['user_id'].count().count()

In [ ]:
filt = df_all['status'] == 'paid'
df_all['user_country'] = df_all['user_country'].str.strip().str.title()
country_report = df_all[filt].groupby('user_country').agg(
    total_orders=('order_id', 'count'),
    total_sales=('final_amount', 'sum'),
    avg_order_amount=('final_amount', 'mean'),
    buyer_count=('user_id', 'nunique')
).sort_values(by='total_sales', ascending=False)
country_report

In [ ]:
filt = df_all['status'] == 'paid'
product_report = df_all[filt].groupby('product_name').agg(
    total_quantity=('quantity', 'sum'),
    total_final_amount=('final_amount', 'sum'),
    total_orders_count=('user_name', 'nunique')
)
product_report

In [ ]:
product_report['total_quantity'].astype(float).nlargest(3)

In [ ]:
product_report['total_final_amount'].astype(float).nlargest(3)

In [ ]:
refunded_products = df_all[df_all['status'] == 'refunded']['product_name'].unique()
refunded_products

In [ ]:
product_report['is_refunded'] = product_report.index.isin(refunded_products)
product_report

In [ ]:
def paidstatus(x):
    if x == 'refunded':
        return True
    return False
df_all['is_refunded'] = df_all['status'].map(lambda x: paidstatus(x))

In [ ]:
df_all

In [ ]:
product_report

In [ ]:
user_report = df_all[df_all['status'] == 'paid'].groupby('user_name').agg(
    total_order_count=('order_id', 'count'),
    total_user_quantity=('quantity', 'sum'),
    total_final_amount=('final_amount', 'sum')
)
user_report['avg_pre_amount'] = user_report['total_final_amount'] / user_report['total_order_count']
user_report

In [ ]:
user_report.loc[user_report['total_final_amount']==user_report['total_final_amount'].max()].index[0]

In [ ]:
user_report.loc[user_report['total_order_count']==user_report['total_order_count'].max()].index[0]

In [ ]:
user_report.loc[user_report['avg_pre_amount']==user_report['avg_pre_amount'].max()].index[0]

In [ ]:
df_all.groupby('user_name').groups

In [ ]:
df_all['final_amount'] = df_all['final_amount'].astype(float)
paid_df = df_all[df_all['status']=='paid']
pivot = pd.pivot_table(paid_df, index='product_category', values='final_amount', columns='user_country', aggfunc='sum', fill_value=0).round(2)
pivot

In [ ]:
df_all.dtypes

In [ ]:
df_all['order_time'] = pd.to_datetime(df_all['order_time'])
month_report = df_all[df_all['status']=='paid'].groupby(
    df_all['order_time'].dt.to_period('M')
).agg(
    total_orders=('order_id', 'count'),
    total_sales=('final_amount', 'sum'),
    buyer_count=('user_id', 'nunique')
)

month_report

In [ ]:
df_all

In [ ]:
paid_df = df_all[df_all['status'] == 'paid'].copy()
paid_df['month'] = paid_df['order_time'].dt.to_period('M')
paid_df

In [ ]:
month_report['total_orders'].idxmax()

In [ ]:
month_report['total_sales'].idxmax()

In [ ]:
month_report['buyer_count'].idxmax()

In [ ]:
month_report2 = df_all[df_all['status'] == 'paid'].groupby(
    pd.Grouper(key='order_time', freq='ME')
).agg(
    total_orders=('order_id', 'count'),
    total_sales=('final_amount', 'sum'),
    buyer_count=('user_id', 'nunique')
)

month_report2

In [ ]:
month_report['avg_order_amount'] = month_report['total_sales'] / month_report['total_orders']
month_report['avg_order_amount'].idxmax()

In [ ]:
month_report

In [36]:
filt = df_all['status'] == 'refunded'
refunded_report = df_all[filt]
refunded_report

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend,...,user_name,user_country,product_name_x,product_category,product_price,user_name,user_country,product_name_y,product_category,product_price
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False,...,Bob,Usa,Keyboard,Electronics,199,Bob,Usa,Keyboard,Electronics,199
8,1009,1,103,1.0,2024-02-15 13:00:00,refunded,200.0,2024-02,13,False,...,Alice,China,Monitor,Electronics,1299,Alice,China,Monitor,Electronics,1299

In [37]:
refunded_report['order_id'].count()

np.int64(2)

In [38]:
refunded_report['final_amount'].sum()

np.float64(1498.0)

In [39]:
refunded_report.groupby('user_country').agg(
    refunded=('final_amount',sum)
)

ValueError: Grouper for 'user_country' not 1-dimensional

In [40]:
refunded_report.groupby('product_name_x').agg(
    refunded=('final_amount',sum)
)

                refunded
product_name_x
Keyboard           199.0
Monitor           1299.0

In [33]:
df_all

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend,...,user_name,user_country,product_name_x,product_category,product_price,user_name,user_country,product_name_y,product_category,product_price
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False,...,Alice,China,Keyboard,Electronics,199,Alice,China,Keyboard,Electronics,199
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False,...,Bob,Usa,Monitor,Electronics,1299,Bob,Usa,Monitor,Electronics,1299
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False,...,Alice,China,Notebook,Stationery,15,Alice,China,Notebook,Stationery,15
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False,...,Cathy,China,Mouse,Electronics,99,Cathy,China,Mouse,Electronics,99
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False,...,David,Uk,Desk,Furniture,899,David,Uk,Desk,Furniture,899
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False,...,Eva,Usa,Chair,Furniture,499,Eva,Usa,Chair,Furniture,499
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False,...,Bob,Usa,Keyboard,Electronics,199,Bob,Usa,Keyboard,Electronics,199
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False,...,Frank,NaN,Notebook,Stationery,15,Frank,NaN,Notebook,Stationery,15
8,1009,1,103,1.0,2024-02-15 13:00:00,paid,200.0,2024-02,13,False,...,Alice,China,Monitor,Electronics,1299,Alice,China,Monitor,Electronics,1299
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False,...,Cathy,China,Chair,Furniture,499,Cathy,China,Chair,Furniture,499
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True,...,Eva,Usa,Keyboard,Electronics,199,Eva,Usa,Keyboard,Electronics,199
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False,...,Bob,Usa,Desk,Furniture,899,Bob,Usa,Desk,Furniture,899

In [34]:
df_all.at[8, 'status'] = 'refunded'

In [35]:
df_all

,order_id,user_id,product_id,quantity,order_time,status,discount,month,hour,is_weekend,...,user_name,user_country,product_name_x,product_category,product_price,user_name,user_country,product_name_y,product_category,product_price
0,1001,1,101,2.0,2024-01-03 10:15:00,paid,0.0,2024-01,10,False,...,Alice,China,Keyboard,Electronics,199,Alice,China,Keyboard,Electronics,199
1,1002,2,103,1.0,2024-01-05 14:20:00,paid,100.0,2024-01,14,False,...,Bob,Usa,Monitor,Electronics,1299,Bob,Usa,Monitor,Electronics,1299
2,1003,1,106,5.0,2024-01-08 09:00:00,paid,0.0,2024-01,09,False,...,Alice,China,Notebook,Stationery,15,Alice,China,Notebook,Stationery,15
3,1004,3,102,3.0,2024-01-08 21:10:00,cancelled,0.0,2024-01,21,False,...,Cathy,China,Mouse,Electronics,99,Cathy,China,Mouse,Electronics,99
4,1005,4,104,1.0,2024-02-01 11:30:00,paid,50.0,2024-02,11,False,...,David,Uk,Desk,Furniture,899,David,Uk,Desk,Furniture,899
5,1006,5,105,2.0,2024-02-03 16:45:00,paid,0.0,2024-02,16,False,...,Eva,Usa,Chair,Furniture,499,Eva,Usa,Chair,Furniture,499
6,1007,2,101,1.0,2024-02-10 08:00:00,refunded,0.0,2024-02,08,False,...,Bob,Usa,Keyboard,Electronics,199,Bob,Usa,Keyboard,Electronics,199
7,1008,6,106,10.0,2024-02-12 19:20:00,paid,5.0,2024-02,19,False,...,Frank,NaN,Notebook,Stationery,15,Frank,NaN,Notebook,Stationery,15
8,1009,1,103,1.0,2024-02-15 13:00:00,refunded,200.0,2024-02,13,False,...,Alice,China,Monitor,Electronics,1299,Alice,China,Monitor,Electronics,1299
9,1010,3,105,1.0,2024-03-01 10:10:00,paid,0.0,2024-03,10,False,...,Cathy,China,Chair,Furniture,499,Cathy,China,Chair,Furniture,499
10,1011,5,101,2.0,2024-03-03 12:00:00,paid,20.0,2024-03,12,True,...,Eva,Usa,Keyboard,Electronics,199,Eva,Usa,Keyboard,Electronics,199
11,1012,2,104,1.0,2024-03-05 18:30:00,paid,0.0,2024-03,18,False,...,Bob,Usa,Desk,Furniture,899,Bob,Usa,Desk,Furniture,899