In [72]:
people = {
    'first': ['Corey', 'Jane', 'John'],
    'last': ['Schafer', 'Doe', 'Smith'],
    'email': ['CoreySchafer@gamil.com', 'JaneDoe@gamil.com', 'JohnSmith@gamil.com']
}

In [82]:
import pandas as pd
import numpy as np

In [74]:
df = pd.DataFrame(people)

In [75]:
df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gamil.com
1   Jane      Doe       JaneDoe@gamil.com
2   John    Smith     JohnSmith@gamil.com

In [10]:
def update_email(email):
    return email.upper()

In [12]:
df['email'].apply(update_email)

0    COREYSCHAFER@GAMIL.COM
1         JANEDOE@GAMIL.COM
2       JOHNSMITH@GAMIL.COM
Name: email, dtype: str

In [13]:
df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gamil.com
1   Jane      Doe       JaneDoe@gamil.com
2   John    Smith     JohnSmith@gamil.com

In [14]:
df['email'] = df['email'].apply(update_email)

In [15]:
df

   first     last                   email
0  Corey  Schafer  COREYSCHAFER@GAMIL.COM
1   Jane      Doe       JANEDOE@GAMIL.COM
2   John    Smith     JOHNSMITH@GAMIL.COM

In [17]:
df['email'] = df['email'].apply(lambda x: x.lower())

In [18]:
df

   first     last                   email
0  Corey  Schafer  coreyschafer@gamil.com
1   Jane      Doe       janedoe@gamil.com
2   John    Smith     johnsmith@gamil.com

In [19]:
df['email'].apply(len)

0    22
1    17
2    19
Name: email, dtype: int64

In [20]:
df.apply(len, axis='columns')

0    3
1    3
2    3
dtype: int64

In [22]:
df.apply(pd.Series.min)

first                     Corey
last                        Doe
email    coreyschafer@gamil.com
dtype: str

In [24]:
df.map(str.lower)

   first     last                   email
0  corey  schafer  coreyschafer@gamil.com
1   jane      doe       janedoe@gamil.com
2   john    smith     johnsmith@gamil.com

In [25]:
df['first'].map({'Corey': 'Chris', 'Jane': 'Mary'})

0    Chris
1     Mary
2      NaN
Name: first, dtype: str

In [26]:
df['first'].replace({'Corey': 'Chris', 'Jane': 'Mary'})

0    Chris
1     Mary
2     John
Name: first, dtype: str

In [28]:
df['first'] + ' ' + df['last']

0    Corey Schafer
1         Jane Doe
2       John Smith
dtype: str

In [29]:
df['full_name'] = df['first'] + ' ' + df['last']

In [30]:
df

   first     last                   email      full_name
0  Corey  Schafer  coreyschafer@gamil.com  Corey Schafer
1   Jane      Doe       janedoe@gamil.com       Jane Doe
2   John    Smith     johnsmith@gamil.com     John Smith

In [32]:
df.drop(columns=['first', 'last'], inplace=True)

In [33]:
df

                    email      full_name
0  coreyschafer@gamil.com  Corey Schafer
1       janedoe@gamil.com       Jane Doe
2     johnsmith@gamil.com     John Smith

In [34]:
df['full_name'].str.split(' ', expand=True)

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John    Smith

In [35]:
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)

In [36]:
df

                    email      full_name  first     last
0  coreyschafer@gamil.com  Corey Schafer  Corey  Schafer
1       janedoe@gamil.com       Jane Doe   Jane      Doe
2     johnsmith@gamil.com     John Smith   John    Smith

In [50]:
pd.concat([df, pd.DataFrame([{'first': 'Tony'}])], ignore_index=True)

                    email      full_name  first     last
0  coreyschafer@gamil.com  Corey Schafer  Corey  Schafer
1       janedoe@gamil.com       Jane Doe   Jane      Doe
2     johnsmith@gamil.com     John Smith   John    Smith
3                     NaN            NaN   Tony      NaN

In [76]:
people = {
    'first': ['Tony','Steve'],
    'last': ['Stack', 'Rogers'],
    'email': ['IronMan@avenage.com', 'Cap@avenage.com']
}
df2 = pd.DataFrame(people)

In [77]:
df2

   first    last                email
0   Tony   Stack  IronMan@avenage.com
1  Steve  Rogers      Cap@avenage.com

In [78]:
pd.concat([df, df2],ignore_index=True)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gamil.com
1   Jane      Doe       JaneDoe@gamil.com
2   John    Smith     JohnSmith@gamil.com
3   Tony    Stack     IronMan@avenage.com
4  Steve   Rogers         Cap@avenage.com

In [79]:
df = pd.concat([df, df2],ignore_index=True)

In [80]:
df

   first     last                   email
0  Corey  Schafer  CoreySchafer@gamil.com
1   Jane      Doe       JaneDoe@gamil.com
2   John    Smith     JohnSmith@gamil.com
3   Tony    Stack     IronMan@avenage.com
4  Steve   Rogers         Cap@avenage.com

In [81]:
df.drop(index=4)

   first     last                   email
0  Corey  Schafer  CoreySchafer@gamil.com
1   Jane      Doe       JaneDoe@gamil.com
2   John    Smith     JohnSmith@gamil.com
3   Tony    Stack     IronMan@avenage.com

In [86]:
people = {
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': ['CoreySchafer@gmail.com', 'JaneDOe@email.com', 'JoneDoe@email.com', None, np.nan, 'Anonymous@email.com', 'NA'],
    'age': ['33', '55', '63', '36', None, None, 'Missing']
}

In [109]:
df = pd.DataFrame(people)

df.replace('NA', np.nan, inplace=True)
df.replace('Missing', np.nan, inplace=True)

   first     last                   email  age
0  Corey  Schafer  CoreySchafer@gmail.com   33
1   Jane      Doe       JaneDOe@email.com   55
2   John      Doe       JoneDoe@email.com   63
3  Chris  Schafer                     NaN   36
4    NaN      NaN                     NaN  NaN
5    NaN      NaN     Anonymous@email.com  NaN
6    NaN      NaN                     NaN  NaN

In [110]:
df

   first     last                   email  age
0  Corey  Schafer  CoreySchafer@gmail.com   33
1   Jane      Doe       JaneDOe@email.com   55
2   John      Doe       JoneDoe@email.com   63
3  Chris  Schafer                     NaN   36
4    NaN      NaN                     NaN  NaN
5    NaN      NaN     Anonymous@email.com  NaN
6    NaN      NaN                     NaN  NaN

In [111]:
df.dropna()

   first     last                   email age
0  Corey  Schafer  CoreySchafer@gmail.com  33
1   Jane      Doe       JaneDOe@email.com  55
2   John      Doe       JoneDoe@email.com  63

In [112]:
df.dropna(axis='index', how='any')

   first     last                   email age
0  Corey  Schafer  CoreySchafer@gmail.com  33
1   Jane      Doe       JaneDOe@email.com  55
2   John      Doe       JoneDoe@email.com  63

In [113]:
df.dropna(axis='index', how='all', subset=['last', 'email'])

   first     last                   email  age
0  Corey  Schafer  CoreySchafer@gmail.com   33
1   Jane      Doe       JaneDOe@email.com   55
2   John      Doe       JoneDoe@email.com   63
3  Chris  Schafer                     NaN   36
5    NaN      NaN     Anonymous@email.com  NaN

In [114]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [115]:
df.fillna(0)

   first     last                   email age
0  Corey  Schafer  CoreySchafer@gmail.com  33
1   Jane      Doe       JaneDOe@email.com  55
2   John      Doe       JoneDoe@email.com  63
3  Chris  Schafer                       0  36
4      0        0                       0   0
5      0        0     Anonymous@email.com   0
6      0        0                       0   0

In [116]:
df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [118]:
 df['age'] = df['age'].astype(float)

In [119]:
df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

In [121]:
df['age'].mean()

np.float64(46.75)